plan(multisession, workers=5)
#cmv<-future_map(stringr::str_subset(list.files("Dif ss/Single_cell_data",full.names = T),"\\+\\+"),read_csv)
#names(cmv)<-stringr::str_subset(list.files("Dif ss/Single_cell_data"),"\\+\\+")%>%str_extract("\\s[^\\.]+")%>%str_trim()

cmv<-future_map(list.files("Dif ss/Single_cell_data",full.names=T),read_csv)
prom<-list.files("Dif ss/Single_cell_data")%>%str_extract("\\s[^\\.]+")%>%str_trim()
cmv2<-map(1:length(unique(prom)),
    ~cmv[which(.x==prom%>%as_factor()%>%as.numeric())]%>%list_rbind()%>%select('FL1-H','FL2-H'))
names(cmv2)<-unique(prom)
ggplot(cmv2$`Weak`,aes(`FL1-H`,`FL2-H`))+geom_point(size=0.25)
ggplot(cmv2$`CMV_Neutral-ss`,aes(`FL1-H`,`FL2-H`))+geom_point(size=0.25)
ggplot(cmv2$`CMV_WT-ss`,aes(`FL1-H`,`FL2-H`))+geom_point(size=0.25)
ggplot(cmv2$`Strong`,aes(`FL1-H`,`FL2-H`))+geom_point(size=0.25)
cmv2<-map2(cmv2,names(cmv2), ~.x%>%mutate(ratio=`FL1-H`/`FL2-H`,prom=.y))
cmv_df<-cmv2%>%list_rbind()
ggplot(cmv_df, aes(ratio,fill=prom))+geom_density(alpha=0.7)+scale_x_log10()
ggplot(cmv_df,aes(`FL1-H`,fill=prom))+geom_density(alpha=0.6)
ggplot(cmv_df,aes(`FL2-H`,fill=prom))+geom_density(alpha=0.6)
cmv_df%>%group_by(prom)%>%summarise(mad=mad(log10(ratio))/median(log10(ratio)))
